# Analisando ações de empresas do Brasil

Existem alguns indicares que demonstram se as ações são boas para investimentos.  
Não existe  uma biografica ou referência que possa trazer uma garantia quanto ao retorno do investimento, uma vez que se trata de investimento de risco e de alta volatibilidade.  
Por este motivo este trabalho busca unicamente apresentar um pouco das ferramentas utilizadas em Python e não busca fazer recomendações para compra de ações.

Importando as bibliotecas necessárias para trabalhar.

In [33]:
# Instale o pandas_datareader e distutils se necessário
!pip install pandas_datareader
!pip install setuptools

Requirement already satisfied: pandas_datareader in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (0.10.0)
Requirement already satisfied: lxml in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas_datareader) (6.0.1)
Requirement already satisfied: pandas>=0.23 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas_datareader) (2.3.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas_datareader) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2025.6.15)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: setuptools in c:\users\rafae\appdata\local\programs\python\python312\lib\site-packages (80.9.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from urllib.request import urlopen
from plotly.offline import iplot
import cufflinks as cf

cf.go_offline()

Para obter os dados foi utilizado um scraping no site Fundamentus (www.fundamentus.com.br) para capturar todas as ações listadas na bolsa de valores brasileira.  
É possível ir direto no site e baixar.

In [17]:
import requests
import pandas as pd
from io import StringIO

url = 'http://www.fundamentus.com.br/resultado.php'
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)

dfs = pd.read_html(StringIO(response.text))
df = dfs[0]

Vamos analisar os dados obtidos.

In [18]:
df.head()

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,14769,000,000,0000,"0,00%",0,000,000,000,...,000,"40,85%","28,98%",260,"22,40%","20,11%",000,"8.420.670.000,00",014,"31,91%"
1,CLAN3,000,000,000,0000,"0,00%",0,000,000,000,...,000,"0,00%","0,00%",0,"0,00%","-1,05%",000,"1.012.240.000,00",000,"-63,96%"
2,PMET3,000,000,000,0000,"0,00%",0,000,000,000,...,000,"0,00%","0,00%",0,"0,00%","4,10%",000,"-290.863.000,00",000,"37,74%"
3,POPR4,1017,000,000,0000,"0,00%",0,000,000,000,...,000,"8,66%","5,65%",108,"15,25%","19,93%",000,"545.803.000,00",082,"30,93%"
4,CSTB3,15000,000,000,0000,"0,00%",0,000,000,000,...,000,"40,85%","28,98%",260,"22,40%","20,11%",000,"8.420.670.000,00",014,"31,91%"

In [19]:
for x in df:
    if df[x].dtype == object:
        df[x] = df[x].str.replace('%','')
        df[x] = df[x].str.replace('.', '')
        df[x] = df[x].str.replace(',', '.')
    if x != 'Papel':    
        df[x] = df[x].astype(float)

ac = ['Cotação', 'P/L', 'P/VP', 'P/Cap.Giro', 'P/EBIT', 'P/Ativ Circ.Liq', 'EV/EBIT', 
       'EV/EBITDA', 'Liq. Corr.', 'Dív.Brut/ Patrim.']   
for x in ac:
    df[x] = df[x].astype(float) / 100

df['P/Ativo'] = df['P/Ativo'].astype(float) / 1000
df['PSR'] = df['PSR'].astype(float) / 1000

Com os dados capturados e tratados vamos utilizar um pouco da análise fundamentalista para classificar as melhores ações na Bolsa de Valores do Brasil.  

#### Valor Justo no último ano  

O valor justo é o valor que a ação vale em relação ao pagamento de dividendos anual.  
Segundo Décio Bazin em seu livro Faça Fortuna com Ações para se obter um valor justo de uma ação com pagamento de dividendos de 6% anualmente deve-se mutiplicar o valor total do dividento por 16,67.

Como o site traz o valor do dividendo em porcentagem fiz a conversão e multipliquei por 16,67.

In [20]:
df['Preco Justo'] = ((df['Cotação'] / 100) * df['Div.Yield']) * 16.67 
df['Preco Justo'] = df['Preco Justo'].round(2)

In [21]:
# Apagar essa parte do codigo.

df = df[['Papel', 'Cotação', 'Preco Justo', 'Div.Yield', 'P/L', 'P/VP', 'PSR', 'P/Ativo',
       'P/Cap.Giro', 'P/EBIT', 'P/Ativ Circ.Liq', 'EV/EBIT', 'EV/EBITDA',
       'Mrg Ebit', 'Mrg. Líq.', 'Liq. Corr.', 'ROIC', 'ROE', 'Liq.2meses',
       'Patrim. Líq', 'Dív.Brut/ Patrim.', 'Cresc. Rec.5a']]

### Roe - Retorno sobre o patrimonio líquido  

O Roe mede a capacidade de agregar valor de uma empresa à partir de seus próprios recursos e do dinheiro de investidores. 
Quanto maior o ROE melhor.

ROE = Lucro Líquido + Patrimônio Líquido

In [22]:
df_roe = df[df['ROE'] > 0]
df_roe

,Papel,Cotação,Preco Justo,Div.Yield,P/L,P/VP,PSR,P/Ativo,P/Cap.Giro,P/EBIT,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.0000,0.000,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
2,PMET3,0.00,0.00,0.00,0.0000,0.000,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,4.10,0.0,-2.908630e+08,0.00,37.74
3,POPR4,10.17,0.00,0.00,0.0000,0.000,0.000,0.000,0.00,0.00,...,0.00,8.66,5.65,1.08,15.25,19.93,0.0,5.458030e+08,0.82,30.93
4,CSTB3,150.00,0.00,0.00,0.0000,0.000,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
5,CFLU4,10.00,0.00,0.00,0.0000,0.000,0.000,0.000,0.00,0.00,...,0.00,8.88,10.72,1.10,17.68,32.15,0.0,6.035100e+07,0.06,8.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,UBBR4,7.49,0.00,0.00,610.2700,1.990,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.33,0.0,1.031720e+10,0.00,10.58
990,VSTE3,5.53,0.03,0.03,11.9975,0.600,0.546,0.376,4.42,12.37,...,4.22,4.41,0.05,1.38,3.35,0.05,60414.8,1.045960e+09,0.33,11.20
991,UBBR11,14.75,0.00,0.00,12.0181,3.910,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.33,0.0,1.031720e+10,0.00,10.58
992,UBBR3,18.00,0.00,0.00,14.6661,4.770,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.33,0.0,1.031720e+10,0.00,10.58
993,BBTG12,3.15,0.00,0.00,2659.8600,265.986,0.000,482.733,0.00,-153.84,...,-153.84,0.00,0.00,0.00,0.00,10.00,0.0,1.000000e+04,0.00,0.00

# P/VPA

O P/VPA é um indicador financeiro que apresenta quanto o mercado está pagando por ação P(preço), sobre o VPA(valor patrimonial por ação).  
O número do resultado é interpretado como multiplicativo, e sempre indica quantas vezes estará pagando, no preço de uma ação pelo valor patrimonial.  
Alguns analista indicam um **valor abaixo ou igual a 1,5** com um bom P/VPA.  
VPA = PL/N° Ações  
Preço/VPA

In [23]:
df_vpa = df_roe[(df_roe['P/VP'] <= 2) & (df_roe['P/VP'] >= 0)]
df_vpa

,Papel,Cotação,Preco Justo,Div.Yield,P/L,P/VP,PSR,P/Ativo,P/Cap.Giro,P/EBIT,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.0000,0.00,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
2,PMET3,0.00,0.00,0.00,0.0000,0.00,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,4.10,0.0,-2.908630e+08,0.00,37.74
3,POPR4,10.17,0.00,0.00,0.0000,0.00,0.000,0.000,0.00,0.00,...,0.00,8.66,5.65,1.08,15.25,19.93,0.0,5.458030e+08,0.82,30.93
4,CSTB3,150.00,0.00,0.00,0.0000,0.00,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
5,CFLU4,10.00,0.00,0.00,0.0000,0.00,0.000,0.000,0.00,0.00,...,0.00,8.88,10.72,1.10,17.68,32.15,0.0,6.035100e+07,0.06,8.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,BIDI3,3.40,0.00,0.00,225.5100,1.06,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.47,0.0,8.348550e+09,0.00,37.00
985,BIDI4,3.41,0.00,0.00,226.1700,1.06,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.47,0.0,8.348550e+09,0.00,37.00
986,BIDI11,10.40,0.00,0.00,229.9300,1.08,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.47,0.0,8.348550e+09,0.00,37.00
989,UBBR4,7.49,0.00,0.00,610.2700,1.99,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.33,0.0,1.031720e+10,0.00,10.58
990,VSTE3,5.53,0.03,0.03,11.9975,0.60,0.546,0.376,4.42,12.37,...,4.22,4.41,0.05,1.38,3.35,0.05,60414.8,1.045960e+09,0.33,11.20

# P/L

P/L - Preço sobre lucro.  
O P/L indica o **número de anos** que um acionista levaria para reaver o capital aplicado em determinada ação.
É um indicador para saber o quanto essa ação pode agregar de valor para o investidor.  
Ele indica o preço de cotação da ação divido elo LPA (lucro do últimos 12 meses) pelo número de ações total.  
P/L = P/LPA

In [43]:
df_pl = df_vpa[df_vpa['P/L'] < 5]
df_pl

,Papel,Cotação,Preco Justo,Div.Yield,P/L,P/VP,PSR,P/Ativo,P/Cap.Giro,P/EBIT,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
2,PMET3,0.00,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,4.10,0.0,-2.908630e+08,0.00,37.74
3,POPR4,10.17,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,...,0.00,8.66,5.65,1.08,15.25,19.93,0.0,5.458030e+08,0.82,30.93
4,CSTB3,150.00,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,...,0.00,40.85,28.98,2.60,22.40,20.11,0.0,8.420670e+09,0.14,31.91
5,CFLU4,10.00,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,...,0.00,8.88,10.72,1.10,17.68,32.15,0.0,6.035100e+07,0.06,8.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,CGRA3,27.85,53.81,11.59,4.87,0.60,0.768,0.439,1.57,6.43,...,3.47,11.95,15.78,2.75,8.59,12.41,33712.6,9.492280e+08,0.00,6.91
495,VBBR3,24.52,21.91,5.36,4.88,1.32,0.152,0.460,2.19,6.53,...,9.73,2.32,3.10,2.09,8.02,26.99,220641000.0,2.084900e+10,1.22,13.01
496,BRSR3,13.17,20.68,9.42,4.90,0.51,0.000,0.000,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,10.33,59349.3,1.064570e+10,0.00,4.64
497,SAPR11,36.67,36.80,6.02,4.90,0.94,1.584,0.445,21.40,5.69,...,6.44,27.86,32.33,1.21,8.41,19.20,42423400.0,1.178430e+10,0.57,9.51
498,COGN3,2.92,1.11,2.28,4.93,0.44,0.814,0.232,3.70,2.49,...,3.77,32.69,18.10,1.53,10.17,8.84,82574100.0,1.256540e+10,0.51,10.68

# Margem Líquida  

Margem líquida é igual ao lucro líquido que a empresa faz num período dividido pela receita líquida.    
A cada real da receita operacional líquida obtido depois de pagar todas as despesas operacionais, financeiro e impostos, há uma margem líquida que representa o quanto esse lucro é em relação a margem líquida.  
Se a margem líquida for de 15%, isso quer dizer que para cada **100,00** que a empresa ganha, ela tem um lucro líquido de **R$ 15,00**.  

Mragem Líquida = Lucro Líquido / Receita Operacional Líquida x 100 (para encontrar em %)

In [48]:
df_ml = df_pl[df_pl['Mrg. Líq.'] > 20]

## Dividendos

Selelção das empresas pagadoras de dividendos acima de 6%.

In [49]:
df_div_yield = df_ml[df_ml['Div.Yield'] > 6]
df_div_yield.sort_values('Div.Yield', ascending=False)

,Papel,Cotação,Preco Justo,Div.Yield,P/L,P/VP,PSR,P/Ativo,P/Cap.Giro,P/EBIT,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
411,TRPN3,0.71,12.40,104.74,0.44,0.54,0.263,0.399,0.59,0.36,...,-0.35,72.28,59.29,3.61,523.01,122.35,0.0,5.935800e+07,0.00,5.77
486,ISAE4,23.26,39.36,10.15,4.72,0.74,1.876,0.349,2.79,3.68,...,6.57,50.96,40.43,5.95,9.95,15.76,38839500.0,2.060200e+10,0.68,17.07
444,BMKS3,436.05,552.44,7.60,2.58,0.77,13.377,0.599,0.87,-10.56,...,-2.45,-126.74,518.61,5.35,-11.26,29.69,16078.1,2.589560e+08,0.01,-10.06
459,JHSF3,5.51,6.71,7.31,3.28,0.63,2.066,0.243,1.13,5.88,...,10.07,35.15,62.54,2.48,4.82,19.08,14747100.0,5.988660e+09,0.93,-2.09
489,SAPR4,7.16,7.50,6.28,4.78,0.92,1.547,0.434,20.89,5.55,...,6.34,27.86,32.33,1.21,8.41,19.20,7405900.0,1.178430e+10,0.57,9.51
497,SAPR11,36.67,36.80,6.02,4.90,0.94,1.584,0.445,21.40,5.69,...,6.44,27.86,32.33,1.21,8.41,19.20,42423400.0,1.178430e+10,0.57,9.51

Vamos plotar o hitórico de Itausa para ver a variação de preço no utlimos 5 anos..

In [ ]:
import pandas_datareader as pdr
price = pd.DataFrame()

tickers = ['ITSA4.SA']
for t in tickers:
    price[t]=pdr.get_data_fred(t, data_source='yahoo', start='2015-1-1')['Adj Close']
    
price.iplot()